#!/bin/bash

if [[ "$1" == "-help" || "$1" == "--help" ]]; then
	echo "use -nap in second argument to not analyze paths"
	exit
fi

if [[ "$2" != "-nap" ]]; then
	python3 WikiParez/appdata/analyzepaths.py
fi

git add *
git commit -m "$1"

read -p "Type Y if you want to push" confirmation
if [[ "$confirmation" == "Y" || "$confirmation" == "y" ]]; then
	git push origin main
fi
